app:
  name: "web_app"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "192.168.0.243"
  port: 3306
  user: "tang"
  password: "123456"
  dbname: "bluebell"
  max_connection: 10,
  max_idle_connection: 2
redis:
  host: "192.168.0.243"
  port: 6379
  db: 0
  password: "123456"
  pool_size: 10

